/* This script is generated */
/* Client Bootstrap configuration */
globalThis.LWR = globalThis.LWR || {};
Object.assign(globalThis.LWR, {"appId":"component-pagination","bootstrapModule":"@lwrjs/app-service/component-pagination/module/esm/v/0_24_1","autoBoot":true,"imports":{"/1/bundle/esm/l/en-US/bi/0/module/mi/%40lwrjs%2Fapp-service%2Fcomponent-pagination%2Fmodule%2Fesm%2Fv%2F0_24_1/s/sha256-Qptly16Sjd70gfjDs5utTqY2sUB0NNeQcvxpFjcvGC8/bundle_@lwrjs_app-service_component-pagination_module_esm.js":["@lwrjs/app-service/component-pagination/module/esm/v/0_24_1"],"/1/bundle/esm/l/en-US/bi/0/module/mi/fandryui%2FcomponentDoc%2Fv%2F0_16_0/s/sha256-ibeHKk6WEQZB2RJO74WykpXen0wmajaU6cf5A04iWRU/bundle_fandryui_componentDoc.js":["fandryui/componentDoc/v/0_16_0"]},"index":{"@lwrjs/app-service/component-pagination/module/esm/v/0_24_1":"/1/module/esm/0/l/en-US/mi/%40lwrjs%2Fapp-service%2Fcomponent-pagination%2Fmodule%2Fesm%2Fv%2F0_24_1/latest/@lwrjs_app-service_component-pagination_module_esm.js","fandryui/componentDoc/v/0_16_0":"/1/module/esm/0/l/en-US/mi/fandryui%2FcomponentDoc%2Fv%2F0_16_0/latest/fandryui_componentDoc.js"},"rootComponents":["fandryui/componentDoc/v/0_16_0"],"serverData":{},"endpoints":{"uris":{"mapping":"/1/mapping/esm/0/l/en-US/bi/0/mp/","module":"/1/bundle/esm/l/en-US/bi/0/module/mi/"}}});
globalThis.LWR = {...globalThis.LWR, env: {"SSR":false,"SSREnabled":false,"basePath":"","locale":"en-US","assetBasePath":"","uiBasePath":""}};
globalThis.process={...globalThis.process,env:{...globalThis.process?.env,...{"NODE_ENV":"prod"}}};
globalThis.lwcRuntimeFlags = { ENABLE_MIXED_SHADOW_MODE: false, ENABLE_WIRE_SYNC_EMIT: false };
// Appended by Static Site Generator
if (!globalThis.LWR.imports) { globalThis.LWR.imports = {}; }
Object.assign(globalThis.LWR.imports, {"/1/bundle/esm/l/en-US/bi/0/module/mi/lwc%2Fv%2F9_4_3/s/sha256-EL643D_kgu-DxtuHjBiYhZdySKDFEWjBscF0aGwGo5I/bundle_lwc.js":["lwc/v/9_4_3"],"/1/bundle/esm/l/en-US/bi/0/module/mi/lwr%2FesmLoader%2Fv%2F0_24_1/s/sha256-in2hntyB9eQqsF8Y6LWW1G0VG-QIuzWvg_GFJRgvE7E/bundle_lwr_esmLoader.js":["lwr/esmLoader/v/0_24_1"],"/1/bundle/esm/l/en-US/bi/0/module/mi/lwr%2Fprofiler%2Fv%2F0_24_1/s/sha256-kGLXJohj797McyfBP40zJ-_7G1vXcR4obQNMGxQNgGk/bundle_lwr_profiler.js":["lwr/profiler/v/0_24_1"]})
if (!globalThis.LWR.index) { globalThis.LWR.index = {}; }
Object.assign(globalThis.LWR.index, {"lwc/v/9_4_3":"/1/module/esm/0/l/en-US/mi/lwc%2Fv%2F9_4_3/latest/lwc.js","lwr/esmLoader/v/0_24_1":"/1/module/esm/0/l/en-US/mi/lwr%2FesmLoader%2Fv%2F0_24_1/latest/lwr_esmLoader.js","lwr/profiler/v/0_24_1":"/1/module/esm/0/l/en-US/mi/lwr%2Fprofiler%2Fv%2F0_24_1/latest/lwr_profiler.js"})
