/* This script is generated */
/* Client Bootstrap configuration */
globalThis.LWR = globalThis.LWR || {};
Object.assign(globalThis.LWR, {"appId":"fandryui","bootstrapModule":"@lwrjs/app-service/fandryui/module/esm/v/0_18_3","autoBoot":true,"imports":{"/1/bundle/esm/l/en-US/bi/0/module/mi/%40lwrjs%2Fapp-service%2Ffandryui%2Fmodule%2Fesm%2Fv%2F0_18_3/s/sha256-kRRAZy1Wsx_dFrzff99-t2cph_2tEKozzmy-BP4hpUM/bundle_@lwrjs_app-service_fandryui_module_esm.js":["@lwrjs/app-service/fandryui/module/esm/v/0_18_3"],"/1/bundle/esm/l/en-US/bi/0/module/mi/fandryui%2Fapp%2Fv%2F0_1_0/s/sha256-Hzkx_25df7Utbkk_aiy4wcqUrVQIr0wQ70nL5T5WYNA/bundle_fandryui_app.js":["fandryui/app/v/0_1_0"]},"index":{"@lwrjs/app-service/fandryui/module/esm/v/0_18_3":"/1/module/esm/0/l/en-US/mi/%40lwrjs%2Fapp-service%2Ffandryui%2Fmodule%2Fesm%2Fv%2F0_18_3/latest/@lwrjs_app-service_fandryui_module_esm.js","fandryui/app/v/0_1_0":"/1/module/esm/0/l/en-US/mi/fandryui%2Fapp%2Fv%2F0_1_0/latest/fandryui_app.js"},"rootComponents":["fandryui/app/v/0_1_0"],"serverData":{},"endpoints":{"uris":{"mapping":"/1/mapping/esm/0/l/en-US/bi/0/mp/","module":"/1/bundle/esm/l/en-US/bi/0/module/mi/"}}});
globalThis.LWR = {...globalThis.LWR, env: {"SSR":false,"SSREnabled":false,"basePath":"","locale":"en-US","assetBasePath":"","uiBasePath":""}};
globalThis.process={...globalThis.process,env:{...globalThis.process?.env,...{"NODE_ENV":"prod"}}};
globalThis.lwcRuntimeFlags = { ENABLE_MIXED_SHADOW_MODE: false, ENABLE_WIRE_SYNC_EMIT: false };
// Appended by Static Site Generator
if (!globalThis.LWR.imports) { globalThis.LWR.imports = {}; }
Object.assign(globalThis.LWR.imports, {"/1/bundle/esm/l/en-US/bi/0/module/mi/lwc%2Fv%2F8_26_2/s/sha256-I71rpgSU5Un9ogV_1-gSMh5Juctv4e8mcuhK8ZeCZgA/bundle_lwc.js":["lwc/v/8_26_2"],"/1/bundle/esm/l/en-US/bi/0/module/mi/lwr%2FesmLoader%2Fv%2F0_18_3/s/sha256-XZ3-fTIQeMpr-t515p72MK4vr6gSnXsH3O_YELtRaFw/bundle_lwr_esmLoader.js":["lwr/esmLoader/v/0_18_3"],"/1/bundle/esm/l/en-US/bi/0/module/mi/lwr%2Fprofiler%2Fv%2F0_18_3/s/sha256-kGLXJohj797McyfBP40zJ-_7G1vXcR4obQNMGxQNgGk/bundle_lwr_profiler.js":["lwr/profiler/v/0_18_3"]})
if (!globalThis.LWR.index) { globalThis.LWR.index = {}; }
Object.assign(globalThis.LWR.index, {"lwc/v/8_26_2":"/1/module/esm/0/l/en-US/mi/lwc%2Fv%2F8_26_2/latest/lwc.js","lwr/esmLoader/v/0_18_3":"/1/module/esm/0/l/en-US/mi/lwr%2FesmLoader%2Fv%2F0_18_3/latest/lwr_esmLoader.js","lwr/profiler/v/0_18_3":"/1/module/esm/0/l/en-US/mi/lwr%2Fprofiler%2Fv%2F0_18_3/latest/lwr_profiler.js"})
